apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-carga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulador-carga
  template:
    metadata:
      labels:
        app: simulador-carga
    spec:
      containers:
      - name: simulador
        image: calculadora-simulador:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: simulador-service
spec:
  selector:
    app: simulador-carga
  ports:
  - port: 5000
    targetPort: 5000